# -*- coding: utf-8 -*-
"""final_wallpaper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoIsDd4s_nCqQyEdE1QCbSLVeX3Xoz1T
"""

import streamlit as st
from openai import OpenAI
from PIL import Image, ImageDraw
import io
import base64
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
import colorsys


# =========================
# OpenAI Client
# =========================

def get_client(api_key: str) -> OpenAI:
    return OpenAI(api_key=api_key)


# =========================
# 이미지/팔레트 유틸
# =========================

def image_to_base64(image: Image.Image) -> str:
    """PIL 이미지를 base64 문자열로 변환"""
    buffered = io.BytesIO()
    image.save(buffered, format="PNG")
    img_bytes = buffered.getvalue()
    return base64.b64encode(img_bytes).decode("utf-8")


def extract_palette_from_images(images, num_colors: int = 5):
    """여러 장의 이미지에서 공통 팔레트 추출 (간단 버전)"""
    all_pixels = []

    for image in images:
        img = image.convert("RGB")
        img = img.resize((130, 130))  # 계산량 줄이기
        arr = np.array(img)
        pixels = arr.reshape(-1, 3)
        all_pixels.extend(map(tuple, pixels))

    if not all_pixels:
        return np.array([])

    counts = Counter(all_pixels)
    most_common = counts.most_common(num_colors)
    colors = np.array([c[0] for c in most_common]) / 255.0  # 0~1 범위
    return colors


def plot_palette(colors):
    """색상 팔레트를 matplotlib으로 시각화"""
    if colors.size == 0:
        return None

    num_colors = len(colors)
    fig, ax = plt.subplots(figsize=(num_colors * 1.2, 1.5))
    ax.set_xlim(0, num_colors)
    ax.set_ylim(0, 1)
    ax.axis("off")

    for i, rgb in enumerate(colors):
        ax.add_patch(plt.Rectangle((i, 0), 1, 1, color=rgb))

    return fig


def colors_to_hex_list(colors):
    """팔레트 색들을 #RRGGBB 리스트로 변환 (프롬프트용)"""
    hex_list = []
    for rgb in colors:
        r, g, b = (rgb * 255).astype(int)
        hex_list.append(f"#{r:02X}{g:02X}{b:02X}")
    return hex_list


# =========================
# 컬러 조정 (무드 파라미터 반영)
# =========================

def adjust_colors_with_mood(colors, brightness_level, saturation_level):
    """
    0~1 brightness / saturation 슬라이더 값을 이용해
    팔레트 색을 전체적으로 조정 (간단한 HLS 조정)
    """
    if colors.size == 0:
        return colors

    adjusted = []
    for rgb in colors:
        r, g, b = rgb
        h, l, s = colorsys.rgb_to_hls(r, g, b)

        # 밝기 조정
        l = (l * 0.5) + (brightness_level * 0.5)
        # 채도 조정
        s = (s * 0.4) + (saturation_level * 0.6)

        r2, g2, b2 = colorsys.hls_to_rgb(h, l, s)
        adjusted.append([r2, g2, b2])

    return np.clip(np.array(adjusted), 0.0, 1.0)


# =========================
# 패턴 & 단색 생성
# =========================

def generate_solid_wallpaper(colors, size=(1024, 1792)):
    """팔레트의 대표 색으로 단색 배경화면 생성"""
    width, height = size
    img = Image.new("RGB", size)

    if colors.size == 0:
        color = (240, 240, 240)
    else:
        # 첫 번째 색을 대표 색으로 사용 (또는 평균 써도 됨)
        rgb = colors[0]
        color = tuple((rgb * 255).astype(int))

    draw = ImageDraw.Draw(img)
    draw.rectangle([0, 0, width, height], fill=color)
    return img


def generate_stripe_pattern(colors, size=(1024, 1792)):
    """팔레트 색으로 스트라이프 패턴 생성"""
    if colors.size == 0:
        colors = np.array([[0.9, 0.9, 0.9]])

    width, height = size
    img = Image.new("RGB", size)
    draw = ImageDraw.Draw(img)

    num_stripes = len(colors)
    stripe_width = int(width / num_stripes) if num_stripes > 0 else width

    for i, rgb in enumerate(colors):
        x0 = i * stripe_width
        x1 = (i + 1) * stripe_width if i < num_stripes - 1 else width
        color = tuple((rgb * 255).astype(int))
        draw.rectangle([x0, 0, x1, height], fill=color)

    return img


def generate_check_pattern(colors, size=(1024, 1792)):
    """팔레트 색으로 체크(격자) 패턴 생성"""
    if colors.size == 0:
        colors = np.array([[0.9, 0.9, 0.9], [0.7, 0.7, 0.7]])

    width, height = size
    img = Image.new("RGB", size)
    draw = ImageDraw.Draw(img)

    num_colors = len(colors)
    num_rows = 10
    num_cols = 6

    cell_w = int(width / num_cols)
    cell_h = int(height / num_rows)

    for row in range(num_rows):
        for col in range(num_cols):
            idx = (row + col) % num_colors
            rgb = colors[idx]
            color = tuple((rgb * 255).astype(int))
            x0 = col * cell_w
            y0 = row * cell_h
            x1 = (col + 1) * cell_w
            y1 = (row + 1) * cell_h
            draw.rectangle([x0, y0, x1, y1], fill=color)

    return img


def generate_dot_pattern(colors, size=(1024, 1792)):
    """팔레트 색으로 도트 패턴 생성"""
    if colors.size == 0:
        colors = np.array([[0.95, 0.95, 0.95], [0.2, 0.2, 0.2]])

    width, height = size
    img = Image.new("RGB", size)
    draw = ImageDraw.Draw(img)

    bg_color = tuple((colors[0] * 255).astype(int))
    draw.rectangle([0, 0, width, height], fill=bg_color)

    dot_colors = colors[1:] if len(colors) > 1 else colors
    num_rows = 12
    num_cols = 7
    radius = int(min(width / (num_cols * 3), height / (num_rows * 3)))

    for row in range(num_rows):
        for col in range(num_cols):
            idx = (row * num_cols + col) % len(dot_colors)
            rgb = dot_colors[idx]
            color = tuple((rgb * 255).astype(int))
            cx = int((col + 0.5) * width / num_cols)
            cy = int((row + 0.5) * height / num_rows)
            draw.ellipse(
                [cx - radius, cy - radius, cx + radius, cy + radius],
                fill=color,
            )

    return img


# =========================
# 무드 파라미터 → 텍스트 설명
# =========================

def describe_mood_params(brightness, saturation, abstractness):
    def level_desc(x):
        if x < 0.33:
            return "low"
        elif x < 0.66:
            return "medium"
        else:
            return "high"

    return (
        f"Brightness: {level_desc(brightness)}, "
        f"Saturation: {level_desc(saturation)}, "
        f"Abstractness: {level_desc(abstractness)}."
    )


def abstractness_phrase(abstractness):
    if abstractness < 0.33:
        return "slightly abstract, closer to realistic composition"
    elif abstractness < 0.66:
        return "moderately abstract with some recognizable structure"
    else:
        return "highly abstract, focusing on shapes and colors rather than objects"


# =========================
# Streamlit UI 설정
# =========================

st.set_page_config(
    page_title="AI Mood Wallpaper Generator",
    page_icon="🎨",
    layout="wide",
)

st.title("🎨 Moodboard 기반 AI 월페이퍼 생성기")
st.write(
    """
여러 장의 이미지를 업로드하면,
공통된 **무드 & 컬러 팔레트**를 분석해서
선택한 방식으로 **배경화면(단색 / 비슷한 무드 이미지 / 추상 / stripe / check / dot)**를 생성합니다.
"""
)

# --- 사이드바: 설정 ---
st.sidebar.header("설정")

api_key = st.sidebar.text_input("OpenAI API Key 입력 (무드/이미지 분석용)", type="password")

style_option = st.sidebar.selectbox(
    "전체 스타일 키워드",
    [
        "Abstract pattern",
        "Soft gradient",
        "Textile / fabric-like pattern",
        "Minimal geometric",
        "Y2K / cute pastel",
    ],
)

generation_mode = st.sidebar.selectbox(
    "배경화면 타입 선택",
    [
        "단색 (Solid color)",
        "비슷한 무드의 이미지 (AI)",
        "추상 배경화면 (AI)",
        "Stripe 패턴",
        "Check 패턴",
        "Dot 패턴",
    ],
)

extra_prompt = st.sidebar.text_input(
    "추가 스타일 텍스트 옵션 (선택)",
    value="",
    help="예: pastel, minimal, cozy, dark, futuristic, dreamy ...",
)

num_palette_colors = st.sidebar.slider("팔레트 색상 개수", 3, 8, 5)

st.sidebar.markdown("---")
st.sidebar.subheader("무드 파라미터")
brightness_level = st.sidebar.slider("Brightness (밝기)", 0.0, 1.0, 0.6, 0.05)
saturation_level = st.sidebar.slider("Saturation (채도)", 0.0, 1.0, 0.7, 0.05)
abstract_level = st.sidebar.slider("Abstractness (추상 정도)", 0.0, 1.0, 0.7, 0.05)

st.sidebar.markdown("---")
st.sidebar.write("1. 이미지 여러 장 업로드 → 2. Generate 버튼 클릭")


# --- 메인 영역: 이미지 업로드 ---
uploaded_files = st.file_uploader(
    "무드를 만들 여러 장의 이미지를 업로드하세요 (룩북, OOTD, 레퍼런스 등)",
    type=["png", "jpg", "jpeg"],
    accept_multiple_files=True,
)

generate_button = st.button("✨ 배경화면 생성하기")


# =========================
# 메인 로직
# =========================

if generate_button:
    if not uploaded_files:
        st.error("이미지를 최소 1장 이상 업로드해 주세요.")
    else:
        # OpenAI 클라이언트 (있으면 생성)
        client = get_client(api_key) if api_key else None

        # PIL 이미지 리스트
        pil_images = [Image.open(f).convert("RGB") for f in uploaded_files]

        col_left, col_right = st.columns(2)

        # --------------------
        # 왼쪽: 원본 이미지들 + 팔레트
        # --------------------
        with col_left:
            st.subheader("① 업로드한 이미지들 (Moodboard)")
            for img in pil_images:
                st.image(img, use_column_width=True)

            # 공통 팔레트 추출 + 무드 조정
            with st.spinner("여러 이미지에서 공통 컬러 팔레트 추출 중..."):
                base_colors = extract_palette_from_images(
                    pil_images, num_colors=num_palette_colors
                )
                adjusted_colors = adjust_colors_with_mood(
                    base_colors, brightness_level, saturation_level
                )
                palette_fig = plot_palette(adjusted_colors)

            st.subheader("② 무드 파라미터 반영된 컬러 팔레트")
            if palette_fig is not None:
                st.pyplot(palette_fig)
            else:
                st.write("팔레트를 추출할 수 없습니다.")

        # --------------------
        # 오른쪽: 무드 분석 + 배경화면 생성
        # --------------------
        with col_right:
            st.subheader("③ 무드 분석 & 배경화면 생성")

            mood_param_text = describe_mood_params(
                brightness_level, saturation_level, abstract_level
            )
            st.markdown("**무드 파라미터 설명**")
            st.write(mood_param_text)

            # 1) AI 무드 분석 (있으면)
            analysis_text = ""
            if client is not None:
                image_contents = []
                for img in pil_images:
                    img_b64 = image_to_base64(img)
                    image_contents.append(
                        {
                            "type": "input_image",
                            "image_url": {"url": f"data:image/png;base64,{img_b64}"},
                        }
                    )

                user_text = (
                    "다음 여러 이미지들의 공통된 무드와 스타일, 컬러 특징을 "
                    "패션/텍스타일 관점에서 요약해 줘. "
                    "최대 5줄 이내로 키워드 위주로 정리해 줘."
                )
                user_text += (
                    f"\n참고 스타일 키워드: {style_option}. "
                    f"\n무드 파라미터: {mood_param_text}"
                )
                if extra_prompt:
                    user_text += f"\n추가 키워드: {extra_prompt}"

                with st.spinner("AI가 무드/스타일을 분석하는 중..."):
                    try:
                        analysis_response = client.chat.completions.create(
                            model="gpt-4o-mini",
                            messages=[
                                {
                                    "role": "system",
                                    "content": (
                                        "You are an expert in fashion, "
                                        "textile design, and color theory. "
                                        "Analyze the shared mood, style, and color palette "
                                        "across the given reference images."
                                    ),
                                },
                                {
                                    "role": "user",
                                    "content": image_contents
                                    + [{"type": "text", "text": user_text}],
                                },
                            ],
                        )
                        analysis_text = (
                            analysis_response.choices[0].message.content.strip()
                        )
                        st.markdown("**AI 무드 & 스타일 분석 결과**")
                        st.write(analysis_text)
                    except Exception as e:
                        st.error(f"무드 분석 중 오류가 발생했습니다: {e}")
                        analysis_text = ""
            else:
                st.info("사이드바에 OpenAI API 키를 입력하면, AI 무드 분석 결과도 볼 수 있습니다.")

            st.markdown("---")
            st.subheader("④ 생성된 배경화면")

            # 2) 선택한 모드에 따라 배경화면 생성
            with st.spinner("배경화면을 생성하는 중..."):
                try:
                    wallpaper_img = None
                    wallpaper_bytes = None

                    # (1) 단색
                    if generation_mode.startswith("단색"):
                        wallpaper_img = generate_solid_wallpaper(adjusted_colors)

                    # (2) 패턴들
                    elif generation_mode.startswith("Stripe"):
                        wallpaper_img = generate_stripe_pattern(adjusted_colors)
                    elif generation_mode.startswith("Check"):
                        wallpaper_img = generate_check_pattern(adjusted_colors)
                    elif generation_mode.startswith("Dot"):
                        wallpaper_img = generate_dot_pattern(adjusted_colors)

                    # (3) AI 기반 이미지 생성 (비슷한 무드 / 추상)
                    elif "비슷한 무드의 이미지" in generation_mode or "추상 배경화면" in generation_mode:
                        if client is None:
                            st.error("AI 이미지 생성을 위해 OpenAI API 키가 필요합니다.")
                        else:
                            palette_hex = colors_to_hex_list(adjusted_colors)
                            palette_text = ", ".join(palette_hex) if palette_hex else "neutral tones"

                            base_prompt = (
                                f"Create a phone wallpaper inspired by the following moodboard. "
                                f"Overall style: {style_option}. "
                                f"Main palette colors: {palette_text}. "
                                f"Mood parameters: {mood_param_text}. "
                                f"Abstractness description: {abstractness_phrase(abstract_level)}. "
                            )

                            if analysis_text:
                                base_prompt += f"\nMoodboard description: {analysis_text}\n"

                            if "비슷한 무드의 이미지" in generation_mode:
                                base_prompt += (
                                    "The wallpaper should feel like a natural extension of the reference images, "
                                    "with similar atmosphere and mood. It can be soft and photographic or lightly stylized, "
                                    "but still usable as a background (not too busy, leave some empty space). "
                                )
                            elif "추상 배경화면" in generation_mode:
                                base_prompt += (
                                    "The wallpaper should be an abstract background that focuses on color, shapes and texture, "
                                    "without recognizable objects. It should work well as a phone wallpaper."
                                )

                            if extra_prompt:
                                base_prompt += f"\nAdditional style keywords: {extra_prompt}."

                            image_response = client.images.generate(
                                model="gpt-image-1",
                                prompt=base_prompt,
                                size="1024x1792",
                                n=1,
                            )
                            generated_b64 = image_response.data[0].b64_json
                            wallpaper_bytes = base64.b64decode(generated_b64)

                    # 공통 표시/다운로드 처리
                    if wallpaper_img is not None:
                        buf = io.BytesIO()
                        wallpaper_img.save(buf, format="PNG")
                        wallpaper_bytes = buf.getvalue()

                    if wallpaper_bytes is not None:
                        st.image(wallpaper_bytes, use_column_width=True)
                        st.download_button(
                            label="📥 배경화면 이미지 다운로드",
                            data=wallpaper_bytes,
                            file_name="wallpaper.png",
                            mime="image/png",
                        )
                    else:
                        st.warning("배경화면을 생성하지 못했습니다.")

                except Exception as e:
                    st.error(f"배경화면 생성 중 오류가 발생했습니다: {e}")